---
# This playbook deploys the whole application stack in this site.


- name: apply common configuration to all nodes
  hosts: all
  gather_facts: false
  become: true
  #remote_user: ec2-user

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: tag_Name_Demo_Linux_Webserver
  gather_facts: true
  #remote_user: ec2-user

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: tag_Name_Demo_Linux_DBserver
  gather_facts: true
  #remote_user: ec2-user

  roles:
    - db
