# demo_setup.yml

- hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Create EC2 instances
      ec2:
         #access_key: "{{ ec2_access_key }}"
         #secret_key: "{{ ec2_secret_key }}"
         key_name: "{{ ec2_keypair }}"
         group_id: "{{ ec2_security_group }}"
         instance_type: "{{ ec2_instance_type }}"
         image: "{{ ec2_image }}"
         region: "{{ ec2_region }}"
         vpc_subnet_id: "{{ ec2_vpc_subnet }}"
         #count: "{{ ec2_instance_count }}"
         wait: false
         assign_public_ip: yes
         #exact_count: "{{ ec2_instance_count }}"
         count_tag:
            Name: "Demo_Linux_{{ item }}"
         instance_tags:
            ansible_group: "{{ item }}"
            Name: "Demo_Linux_{{ item }}"
      with_items:
        - "{{ server_roles }}"
      register: ec2
      #async: 7200
      poll: 0

#    - name: Add all instances public IPs to host group
#      add_host: hostname="{{ item.public_ip }}" groupname=dbservers
#      with_items: "{{ ec2.instances }}"
#      #with_items: "{{ tag_Name_Dbserver }}"

    - name: Wait for instance creation to complete
      delegate_to: localhost
      become: no
      wait_for_connection:
        delay: 10
        timeout: 300
